MONTHLY_RENT_DEFAULT = 1250
HOUSE_VALUE_DEFAULT = 400000
YOUNGER_THAN_32_DEFAULT = True
EXTRA_MONTHLY_COSTS_DEFAULT = 150
OVERBID_DEFAULT = int(HOUSE_VALUE_DEFAULT * 0.1)
RENNOVATION_PRICE_DEFAULT = 0
YEARLY_HOUSE_APPRECIATION_DEFAULT = 3.0
YEARLY_STOCK_INCREASE_DEFAULT = 8.0
